<template>
  <v-input
    v-if="isEditing && !disabled"
    :autofocus="true"
    :model-value="value"
    :placeholder="placeholder"
    :slug="true"
    :trim="trim"
    class="input"
    slug-separator="-"
    @blur="endEditing"
    @keydown.enter="endEditing"
    @keydown.esc="cancelEditing"
    @update:model-value="onValueChange">
    <template v-if="iconLeft || prefix" #prepend>
      <v-icon v-if="iconLeft" :name="iconLeft" />
      <span class="input__prefix">{{ renderedPrefix }}</span>
    </template>
    <template v-if="suffix" #append>
      <span class="input__suffix">{{ renderedSuffix }}</span>
    </template>
  </v-input>
  <div v-else class="preview">
    <v-icon v-if="iconLeft" :name="iconLeft" class="preview__icon" />
    <a v-if="previewURL" target="_blank" class="preview__link" :href="previewURL">{{ previewURL }}</a>
    <span v-else class="preview__text">{{ previewText }}</span>
    <v-button v-if="!disabled" v-tooltip="t('edit')" x-small secondary icon class="action-button" @click="beginEditing">
      <v-icon name="edit" />
    </v-button>
    <v-button
      v-if="!isDirty && isSourceSlugDifferent"
      v-tooltip="t('auto_generate')"
      x-small
      secondary
      icon
      class="action-button"
      @click="resetToAutoGenerated">
      <v-icon name="auto_fix_high" />
    </v-button>
  </div>
</template>

<script lang="ts">
import { PropType, defineComponent, computed, inject, reactive, ref, watch, nextTick } from 'vue'
import { useI18n } from 'vue-i18n'
import { render, renderFn, get } from 'micromustache'
import slugify from '@sindresorhus/slugify'

export default defineComponent({
  props: {
    primaryKey: {
      type: String,
      default: null
    },
    autofocus: {
      type: Boolean,
      default: false
    },
    autoGenerate: {
      type: Array as PropType<string[]>,
      default: () => ['create']
    },
    disabled: {
      type: Boolean,
      default: false
    },
    field: {
      type: String,
      required: true
    },
    iconLeft: {
      type: String,
      default: null
    },
    length: {
      type: Number,
      default: null
    },
    placeholder: {
      type: String,
      default: null
    },
    prefix: {
      type: String,
      default: null
    },
    source: {
      type: String,
      default: null
    },
    suffix: {
      type: String,
      default: null
    },
    value: {
      type: String,
      default: null
    },
    customReplacements: {
      type: Array as PropType<{ source: string; target: string }[]>,
      default: () => []
    }
  },
  emits: ['input'],
  setup(props, { emit }) {
    const { t } = useI18n()
    const values = inject('values', ref<Record<string, any>>({}))
    const trim = ref(false)
    const isDirty = ref(false)
    const isEditing = ref(false)
    const checkpoint = reactive({
      value: props.value,
      isDirty: false
    })

    function transformValue(value: string) {
      const customReplacements = props.customReplacements.map((replacement): [string, string] => [replacement.source, replacement.target])
      return slugify(value, { separator: '-', preserveTrailingDash: true, customReplacements }).slice(0, props.length)
    }

    function resolverWithDefaults(name: string, scope?: Record<string, any>) {
      const value = scope ? get(scope, name) : undefined
      return value !== undefined ? value : `[${name}]`
    }

    const renderedPrefix = computed(() => renderFn(props.prefix || '', resolverWithDefaults, values.value))
    const renderedSuffix = computed(() => renderFn(props.suffix || '', resolverWithDefaults, values.value))

    const preview = computed(() => (props.value ? renderedPrefix.value + props.value + renderedSuffix.value : null))
    const previewText = computed(() => preview.value ?? t('enter_a_value'))
    const previewURL = computed(() => (/^https?:\/\//.test(renderedPrefix.value) ? preview.value : null))

    const sourceSlug = computed(() => (props.source ? transformValue(render(props.source, values.value)) : ''))
    const isSourceSlugDifferent = computed(() => {
      const sourceSlugValue = sourceSlug.value
      const currentSlugValue = props.value || ''

      // Don't strip numeric suffixes, as they may not always be to prevent duplication (such as year-based slugs).
      if (sourceSlugValue === currentSlugValue) return false
      if (sourceSlugValue === currentSlugValue.replace(/-\d+$/, '')) return false

      return true
    })

    watch(values, (values) => {
      // Only auto-generate when the value is unmodified.
      if (isDirty.value || isEditing.value) return

      // Only auto-generate when the field's settings allow it.
      const action = props.primaryKey === '+' ? 'create' : 'update'
      if (!props.autoGenerate.includes(action)) return

      // Ignore changes from the slug field itself by comparing with the value from `props`.
      // This works because Vue defers updates to props, but the watch callback runs immediately.
      if (values[props.field] && values[props.field] !== props.value) return

      // Only emit an update when the source produces a different slug.
      if (sourceSlug.value === props.value) return

      emit('input', sourceSlug.value)
    })

    function beginEditing() {
      checkpoint.value = props.value
      checkpoint.isDirty = isDirty.value
      isEditing.value = true
    }

    function endEditing() {
      isEditing.value = false
    }

    function cancelEditing() {
      // Trim must be disabled to avoid modifying the restored value.
      trim.value = false
      isDirty.value = checkpoint.isDirty
      emit('input', checkpoint.value)

      // Disable editing on the next tick to allow the input to update first.
      nextTick(() => {
        isEditing.value = false
        trim.value = true
      })
    }

    function onValueChange(value: string | null) {
      if (props.disabled) return
      if (props.value === value) return

      isDirty.value = typeof value === 'string' && value.length > 0
      emit('input', typeof value === 'string' ? transformValue(value) : null)
    }

    function resetToAutoGenerated() {
      isDirty.value = false
      emit('input', sourceSlug.value)
    }

    return {
      t,
      trim,
      isDirty,
      isEditing,
      renderedPrefix,
      renderedSuffix,
      previewText,
      previewURL,
      isSourceSlugDifferent,
      beginEditing,
      endEditing,
      cancelEditing,
      onValueChange,
      resetToAutoGenerated
    }
  }
})
</script>

<style lang="css" scoped>
.input__prefix,
.input__suffix {
  flex: 1 1 auto;
  color: var(--foreground-subdued);
}

.preview {
  display: flex;
  gap: 0.75em;
  align-items: center;
  padding: var(--theme--form--field--input--padding);
  border: var(--theme--border-width) solid var(--v-input-border-color, var(--theme--form--field--input--border-color));
  border-radius: var(--v-input-border-radius, var(--theme--border-radius));
  block-size: var(--theme--form--field--input--height);
  inline-size: 100%;
}

.preview__text {
  flex: 1 1 auto;
}
</style>
